#!/bin/bash

# Small utility script to run the project using the compile-time classpath
# without resorting to SBT every time.
# This is useful because the fat-jar does not include Spark and Hadoop, since
# those are provided dependencies

pushd $(dirname $0) > /dev/null

CLASSPATH_FILE="$(pwd)/.run-classpath"

if [[ ! -f $CLASSPATH_FILE ]]
then
  echo "Exporting classpath"
  sbt "export experiments/fullClasspath" | tail -n 1 > $CLASSPATH_FILE
fi

CLASSPATH=$(cat $CLASSPATH_FILE)

popd > /dev/null

java \
	-Dspark.master="local[*]" \
  -Dspark.driver.host=127.0.0.1 \
	-Dspark.serializer=org.apache.spark.serializer.KryoSerializer\
	-Dexperiment.reporter.compress=false\
	-Xmx4G \
	-XX:+UseG1GC \
	-cp $CLASSPATH it.unipd.dei.clustering.$1 ${@:2}

